name: my_portfolio
description: A portfolio showcasing HPC and Fullstack developer skills
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  url_launcher: ^6.1.11
  flutter_svg: ^2.0.5
  animated_text_kit: ^4.0.0
  flutter_staggered_grid_view: ^0.6.2  
  carousel_slider: ^4.2.1
  icons_plus: ^4.0.0
  flutter_screenutil: ^5.5.4
  provider: ^6.0.0
  flutter_animate: ^4.4.1
  flutter_launcher_icons: ^0.13.1
  http: ^0.13.6
  path_provider: ^2.1.1
  get: ^4.7.3
  lottie: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/Logo.jpg"
    background_color: "#8B4513"
    theme_color: "#8B4513"
  remove_alpha_ios: true
  image_path: "assets/Logo.jpg"

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/images/projects/
    - assets/fonts/
    - assets/portfolio/
    - assets/translations/
  fonts:
    - family: PlusJakartaSans-Bold
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
    - family: PlusJakartaSans-Regular
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
    - family: PlusJakartaSans-Medium
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
    - family: PlusJakartaSans-semiBold
      fonts:
        - asset: assets/fonts/PlusJakartaSans-semiBold.ttf